import { expect, test } from "@playwright/test";
import { decreaseColors, increaseColors, neutralChangeColor } from "../../lib/map-colors";

test("dashboard map and routes work", async ({ page }) => {
  const browserErrors: string[] = [];
  page.on("console", (message) => {
    if (message.type() === "error") browserErrors.push(message.text());
  });
  page.on("pageerror", (error) => browserErrors.push(error.message));

  await page.goto("/");
  await expect(page.getByRole("heading", { name: /clearer view/i })).toBeVisible();
  await expect(page.getByText(/Geography crosswalk resolved/i)).toHaveCount(0);
  await expect(page.getByText("Map preview", { exact: true })).toHaveCount(0);
  await expect(page.locator("path[data-neighborhood-id]")).toHaveCount(50);
  await expect(page.getByText(/Decrease.*signed change.*increase/i)).toBeVisible();
  await expect(page.getByLabel("Change-rate color legend")).toContainText("−2.5");
  await expect(page.getByLabel("Change-rate color legend")).toContainText("+50+");
  await expect(page.getByLabel("Map measure")).toHaveValue("change");
  await page.getByLabel("Crime type").selectOption("robbery");
  await expect(page).toHaveURL(/crime=robbery/);
  const mountAiry = page.locator("#neighborhood-mt-airy");
  await mountAiry.dispatchEvent("click");
  await expect(page.getByRole("heading", { name: "Mt. Airy" })).toBeVisible();
  const fills = await page.locator("path[data-neighborhood-id]").evaluateAll((paths) => [...new Set(paths.map((path) => path.getAttribute("fill")))]);
  expect(fills).toContain(neutralChangeColor);
  expect(fills.some((fill) => decreaseColors.includes(fill ?? ""))).toBe(true);
  expect(fills.some((fill) => increaseColors.includes(fill ?? ""))).toBe(true);
  await page.getByLabel("Map measure").selectOption("count");
  await expect(page.locator("#neighborhood-mt-airy")).toHaveAttribute("aria-label", /YTD: \d+; Change from prior YTD:/);
  await page.getByLabel("Map measure").selectOption("rate");
  await expect(page).toHaveURL(/measure=rate/);
  await expect(page.locator("#neighborhood-mt-airy")).toHaveAttribute("aria-label", /per 1,000: .*Change from prior YTD:/);
  await page.getByRole("button", { name: "Calendar year" }).click();
  await page.getByLabel("Calendar year").selectOption("2011");
  await expect(page).toHaveURL(/period=annual/);
  await expect(page).toHaveURL(/year=2011/);
  await mountAiry.dispatchEvent("click");
  await expect(page.getByText("Selected area · 2011")).toBeVisible();
  await page.goto("/neighborhood/mt-airy/?period=annual&year=2019&crime=robbery");
  await expect(page.getByRole("heading", { name: "Mt. Airy" })).toBeVisible();
  await expect(page.getByLabel("Calendar year")).toHaveValue("2019");
  await expect(page.getByLabel("Crime type")).toHaveValue("robbery");
  await page.goto("/rankings/");
  await expect(page.getByRole("heading", { name: "Neighborhood rankings" })).toBeVisible();
  await page.getByLabel("Crime type").selectOption("homicide");
  await expect(page.locator("caption").filter({ hasText: "Homicide by statistical area" })).toBeVisible();
  await page.goto("/trends/");
  await expect(page.getByRole("heading", { name: "Long-term trends" })).toBeVisible();
  await expect(page.locator(".recharts-line-curve")).toBeVisible();
  await page.getByLabel("Crime type").selectOption("motor_vehicle_theft");
  await expect(page.getByRole("heading", { name: /Citywide · Motor vehicle theft/i })).toBeVisible();
  await page.getByLabel("Series").selectOption("sameDateYtd");
  await expect(page.getByRole("cell", { name: "2026" })).toBeVisible();
  await page.goto("/demographics/");
  await expect(page.getByRole("heading", { name: "Neighborhood demographics" })).toBeVisible();
  await page.getByLabel("Demographic area").selectOption("avondale");
  await expect(page.getByText(/Estimates with 90% margins of error/i)).toBeVisible();
  await page.getByLabel("Demographic area").selectOption("westwood");
  await expect(page.getByText(/official SNA profile is image-only/i)).toBeVisible();
  await page.goto("/data-status/");
  await expect(page.getByRole("row", { name: /Historical same-date YTD/i })).toBeVisible();
  await expect(page.getByRole("row", { name: /Presidential precinct canvasses/i })).toBeVisible();
  await expect(page.getByText(/Latest generated artifact/i)).toBeVisible();

  await page.goto("/elections/");
  await expect(page.getByRole("heading", { name: "Neighborhood elections explorer" })).toBeVisible();
  await expect(page.getByLabel("Election year")).toHaveValue("2024");
  await expect(page.getByLabel("2024 Cincinnati neighborhood election map").locator("path[role='button']")).toHaveCount(50);
  await page.getByLabel("Election map measure").selectOption("democratic");
  await expect(page.getByText("Democratic ticket share (%)")).toBeVisible();
  await page.getByLabel("Election year").selectOption("2016");
  await expect(page.getByText("2016 neighborhood estimates")).toBeVisible();
  await page.getByLabel("Election area").selectOption("mt-airy");
  await expect(page.getByRole("heading", { name: "Mt. Airy voting trend" })).toBeVisible();

  await page.goto("/neighborhood/mt-airy/");
  await expect(page.getByRole("heading", { name: "Presidential voting" })).toBeVisible();
  await expect(page.getByLabel("Neighborhood election year")).toHaveValue("2024");
  expect(browserErrors).toEqual([]);
});
