import { expect, test } from "@playwright/test";
import { decreaseColors, increaseColors, neutralChangeColor } from "../../lib/map-colors";

test("dashboard map and routes work", async ({ page }) => {
  const browserErrors: string[] = [];
  page.on("console", (message) => {
    if (message.type() === "error") browserErrors.push(message.text());
  });
  page.on("pageerror", (error) => browserErrors.push(error.message));

  await page.goto("/");
  await expect(page.getByRole("heading", { name: /clearer view/i })).toBeVisible();
  await expect(page.getByText(/Geography crosswalk resolved/i)).toHaveCount(0);
  await expect(page.getByText("Map preview", { exact: true })).toHaveCount(0);
  await expect(page.locator("path[data-neighborhood-id]")).toHaveCount(50);
  await expect(page.getByText(/Decrease.*signed change.*increase/i)).toBeVisible();
  await expect(page.getByLabel("Change-rate color legend")).toContainText("−2.5");
  await expect(page.getByLabel("Change-rate color legend")).toContainText("+50+");
  await expect(page.getByLabel("Map measure")).toHaveValue("change");
  await page.getByLabel("Crime type").selectOption("robbery");
  await expect(page).toHaveURL(/crime=robbery/);
  const mountAiry = page.locator("#neighborhood-mt-airy");
  await mountAiry.dispatchEvent("click");
  await expect(page.getByRole("heading", { name: "Mt. Airy" })).toBeVisible();
  const fills = await page.locator("path[data-neighborhood-id]").evaluateAll((paths) => [...new Set(paths.map((path) => path.getAttribute("fill")))]);
  expect(fills).toContain(neutralChangeColor);
  expect(fills.some((fill) => decreaseColors.includes(fill ?? ""))).toBe(true);
  expect(fills.some((fill) => increaseColors.includes(fill ?? ""))).toBe(true);
  const changeFills = await page.locator("path[data-neighborhood-id]").evaluateAll((paths) => paths.map((path) => path.getAttribute("fill")));
  await page.getByLabel("Map measure").selectOption("count");
  await expect(page.getByLabel("Reported count color legend")).toContainText(/signed count change/i);
  const countFills = await page.locator("path[data-neighborhood-id]").evaluateAll((paths) => paths.map((path) => path.getAttribute("fill")));
  expect(countFills).not.toEqual(changeFills);
  expect(countFills.some((fill) => decreaseColors.includes(fill ?? ""))).toBe(true);
  expect(countFills.some((fill) => increaseColors.includes(fill ?? ""))).toBe(true);
  await expect(page.locator("#neighborhood-mt-airy")).toHaveAttribute("aria-label", /YTD: \d+; Count change from prior YTD: [+-]?\d+ offenses/);
  await page.getByLabel("Map measure").selectOption("rate");
  await expect(page.getByLabel("Rate per 1,000 color legend")).toContainText(/signed rate change per 1,000/i);
  const rateFills = await page.locator("path[data-neighborhood-id]").evaluateAll((paths) => paths.map((path) => path.getAttribute("fill")));
  expect(rateFills).not.toEqual(countFills);
  expect(rateFills.some((fill) => decreaseColors.includes(fill ?? ""))).toBe(true);
  expect(rateFills.some((fill) => increaseColors.includes(fill ?? ""))).toBe(true);
  await expect(page).toHaveURL(/measure=rate/);
  await expect(page.locator("#neighborhood-mt-airy")).toHaveAttribute("aria-label", /per 1,000: .*Rate change from prior YTD: [+-]?\d+\.\d per 1,000/);
  await page.getByRole("button", { name: "Calendar year" }).click();
  await page.getByLabel("Calendar year").selectOption("2011");
  await expect(page).toHaveURL(/period=annual/);
  await expect(page).toHaveURL(/year=2011/);
  await mountAiry.dispatchEvent("click");
  await expect(page.getByText("Selected area · 2011")).toBeVisible();
  await page.goto("/neighborhood/mt-airy/?period=annual&year=2019&crime=robbery");
  await expect(page.getByRole("heading", { name: "Mt. Airy" })).toBeVisible();
  await expect(page.getByLabel("Calendar year")).toHaveValue("2019");
  await expect(page.getByLabel("Crime type")).toHaveValue("robbery");
  await page.goto("/rankings/");
  await expect(page.getByRole("heading", { name: "Neighborhood rankings" })).toBeVisible();
  await page.getByLabel("Crime type").selectOption("homicide");
  await expect(page.locator("caption").filter({ hasText: "Homicide by statistical area" })).toBeVisible();
  await page.goto("/trends/");
  await expect(page.getByRole("heading", { name: "Long-term trends" })).toBeVisible();
  await expect(page.locator(".recharts-line-curve")).toBeVisible();
  await page.getByLabel("Crime type").selectOption("motor_vehicle_theft");
  await expect(page.getByRole("heading", { name: /Citywide · Motor vehicle theft/i })).toBeVisible();
  await page.getByLabel("Series").selectOption("sameDateYtd");
  await expect(page.getByRole("cell", { name: "2026" })).toBeVisible();
  await page.goto("/demographics/");
  await expect(page.getByRole("heading", { name: "Neighborhood demographics" })).toBeVisible();
  await page.getByLabel("Demographic area").selectOption("avondale");
  await expect(page.getByText(/Estimates with 90% margins of error/i)).toBeVisible();
  await page.getByLabel("Demographic area").selectOption("westwood");
  await expect(page.getByText(/official SNA profile is image-only/i)).toBeVisible();
  await page.goto("/data-status/");
  await expect(page.getByRole("row", { name: /Historical same-date YTD/i })).toBeVisible();
  await expect(page.getByRole("row", { name: /General-election canvasses/i })).toBeVisible();
  await expect(page.getByRole("row", { name: /Police budget ledger/i })).toBeVisible();
  await expect(page.getByText(/Latest generated artifact/i)).toBeVisible();

  await page.goto("/budget/");
  await expect(page.getByRole("heading", { name: "Police budget and neighborhood allocation" })).toBeVisible();
  await expect(page.getByLabel("Budget fiscal year")).toHaveValue("2025");
  await page.getByLabel("Budget fiscal year").selectOption("2024");
  await page.getByLabel("Budget crime allocation basis").selectOption("violent");
  await page.getByLabel("Budget selected area").selectOption("westwood");
  await expect(page.getByText("Selected neighborhood", { exact: true })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Westwood" })).toBeVisible();
  await expect(page.getByText(/Modeled allocation—not actual spending/i)).toBeVisible();

  await page.goto("/elections/");
  await expect(page.getByRole("heading", { name: "Neighborhood elections explorer" })).toBeVisible();
  await expect(page.getByLabel("Election and contest")).toHaveValue("2024-president");
  const electionMap = page.getByLabel("2024 President Cincinnati neighborhood election map");
  await expect(electionMap.locator("path[role='button']")).toHaveCount(50);
  await page.getByLabel("Election map measure").selectOption("democratic");
  await expect(page.getByText("Democratic share (%)")).toBeVisible();
  await page.getByLabel("Election and contest").selectOption("2022-governor");
  await expect(page.getByText("2022 Governor neighborhood estimates")).toBeVisible();
  await page.getByLabel("Election and contest").selectOption("2018-us_senate");
  await page.getByLabel("Election area").selectOption("mt-airy");
  await expect(page.getByRole("heading", { name: "Mt. Airy u.s. senate trend" })).toBeVisible();
  const selectedPath = page.getByLabel("2018 U.S. Senate Cincinnati neighborhood election map").getByRole("button", { name: /^Mt\. Airy:/ });
  await selectedPath.focus();
  expect(await selectedPath.evaluate((element) => getComputedStyle(element).outlineStyle)).toBe("none");

  await page.goto("/neighborhood/mt-airy/");
  await expect(page.getByRole("heading", { name: "Election voting" })).toBeVisible();
  await expect(page.getByLabel("Neighborhood election and contest")).toHaveValue("2024-president");
  expect(browserErrors).toEqual([]);
});
