import { expect, test } from "@playwright/test";

test("dashboard map and routes work", async ({ page }) => {
  const browserErrors: string[] = [];
  page.on("console", (message) => {
    if (message.type() === "error") browserErrors.push(message.text());
  });
  page.on("pageerror", (error) => browserErrors.push(error.message));

  await page.goto("/");
  await expect(page.getByRole("heading", { name: /clearer view/i })).toBeVisible();
  await expect(page.getByText(/Geography crosswalk resolved/i)).toHaveCount(0);
  await expect(page.locator("path[data-neighborhood-id]")).toHaveCount(50);
  await expect(page.getByText(/Decrease.*change rate.*increase/i)).toBeVisible();
  await expect(page.getByLabel("Map measure")).toHaveValue("change");
  await page.getByLabel("Crime type").selectOption("robbery");
  await expect(page).toHaveURL(/crime=robbery/);
  const mountAiry = page.locator("#neighborhood-mt-airy");
  await mountAiry.dispatchEvent("click");
  await expect(page.getByRole("heading", { name: "Mt. Airy" })).toBeVisible();
  const fills = await page.locator("path[data-neighborhood-id]").evaluateAll((paths) => [...new Set(paths.map((path) => path.getAttribute("fill")))]);
  expect(fills).toContain("#087a4f");
  expect(fills.some((fill) => fill === "#e45145" || fill === "#b51f2e" || fill === "#f1a08f")).toBe(true);
  await page.getByLabel("Map measure").selectOption("rate");
  await expect(page).toHaveURL(/measure=rate/);
  await page.getByRole("button", { name: "Calendar year" }).click();
  await page.getByLabel("Calendar year").selectOption("2011");
  await expect(page).toHaveURL(/period=annual/);
  await expect(page).toHaveURL(/year=2011/);
  await mountAiry.dispatchEvent("click");
  await expect(page.getByText("Selected area · 2011")).toBeVisible();
  await page.goto("/neighborhood/mt-airy/?period=annual&year=2019&crime=robbery");
  await expect(page.getByRole("heading", { name: "Mt. Airy" })).toBeVisible();
  await expect(page.getByLabel("Calendar year")).toHaveValue("2019");
  await expect(page.getByLabel("Crime type")).toHaveValue("robbery");
  await page.goto("/rankings/");
  await expect(page.getByRole("heading", { name: "Neighborhood rankings" })).toBeVisible();
  await page.getByLabel("Crime type").selectOption("homicide");
  await expect(page.locator("caption").filter({ hasText: "Homicide by statistical area" })).toBeVisible();
  await page.goto("/trends/");
  await expect(page.getByRole("heading", { name: "Long-term trends" })).toBeVisible();
  await expect(page.locator(".recharts-line-curve")).toBeVisible();
  await page.getByLabel("Crime type").selectOption("motor_vehicle_theft");
  await expect(page.getByRole("heading", { name: /Citywide · Motor vehicle theft/i })).toBeVisible();
  await page.getByLabel("Series").selectOption("sameDateYtd");
  await expect(page.getByRole("cell", { name: "2026" })).toBeVisible();
  await page.goto("/data-status/");
  await expect(page.getByRole("row", { name: /Historical same-date YTD/i })).toBeVisible();
  await expect(page.getByText(/Latest generated artifact/i)).toBeVisible();
  expect(browserErrors).toEqual([]);
});
