"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { electionMetric, electionOptionLabel, formatElectionPercent, type ElectionAreaResult, type ElectionMeasure, type ElectionResult, type ElectionsData } from "@/lib/elections";
import { electionBlueScale as blueScale, electionFill, electionGoldScale as goldScale, electionMarginLegend as marginLegend, electionRedScale as redScale, electionTealScale as tealScale } from "@/lib/map-colors";

type Region = { id: string; slug: string; name: string; path: string };
export type ElectionMapData = { viewBox: string; regions: Region[] };

export function ElectionExplorer({ data, mapData }: { data: ElectionsData; mapData: ElectionMapData }) {
  const [electionId, setElectionId] = useState(data.elections.at(-1)!.id);
  const [measure, setMeasure] = useState<ElectionMeasure>("margin");
  const [slug, setSlug] = useState("citywide");
  const [focusedSlug, setFocusedSlug] = useState<string | null>(null);
  const election = data.elections.find((row) => row.id === electionId)!;
  const area = slug === "citywide" ? election.citywide : election.neighborhoods.find((row) => row.slug === slug) ?? election.citywide;
  const values = useMemo(() => new Map(election.neighborhoods.map((row) => [row.id, electionMetric(row, measure)])), [election, measure]);
  const trend = data.elections.filter((row) => row.contestId === election.contestId).map((row) => ({ year: row.year, ...(slug === "citywide" ? row.citywide : row.neighborhoods.find((item) => item.slug === slug) ?? row.citywide) }));

  return <div>
    <div className="mb-5 grid gap-4 border border-[#d2dcdb] bg-white p-4 md:grid-cols-2 xl:grid-cols-[240px_260px_minmax(240px,1fr)] xl:items-end">
      <label><span className="mb-1.5 block text-[0.68rem] font-black uppercase tracking-[0.12em] text-[#5b7278]">Election and contest</span><select aria-label="Election and contest" value={electionId} onChange={(event) => setElectionId(event.target.value)} className="w-full rounded-sm border border-[#aebfbd] bg-white px-3 py-2 text-sm font-bold text-[#173d4a]">{[...data.elections].reverse().map((item) => <option key={item.id} value={item.id}>{electionOptionLabel(item)}</option>)}</select></label>
      <label><span className="mb-1.5 block text-[0.68rem] font-black uppercase tracking-[0.12em] text-[#5b7278]">Map measure</span><select aria-label="Election map measure" value={measure} onChange={(event) => setMeasure(event.target.value as ElectionMeasure)} className="w-full rounded-sm border border-[#aebfbd] bg-white px-3 py-2 text-sm font-bold text-[#173d4a]"><option value="margin">Democratic–Republican margin</option><option value="turnout">Turnout</option><option value="democratic">Democratic share</option><option value="republican">Republican share</option><option value="other">Other / independent share</option></select></label>
      <label><span className="mb-1.5 block text-[0.68rem] font-black uppercase tracking-[0.12em] text-[#5b7278]">Selected area</span><select aria-label="Election area" value={slug} onChange={(event) => setSlug(event.target.value)} className="w-full rounded-sm border border-[#aebfbd] bg-white px-3 py-2 text-sm font-bold text-[#173d4a]"><option value="citywide">Citywide</option>{election.neighborhoods.map((row) => <option key={row.id} value={row.slug}>{row.name}</option>)}</select></label>
    </div>

    <div className="grid gap-5 lg:grid-cols-[minmax(0,1.62fr)_minmax(340px,0.78fr)]">
      <div className="relative min-h-[560px] overflow-hidden rounded-sm bg-[#eef3f2] lg:min-h-[680px]">
        <ElectionLegend measure={measure}/>
        <svg viewBox={mapData.viewBox} className="h-full min-h-[560px] w-full p-5 lg:min-h-[680px] lg:p-8" role="img" aria-label={`${election.year} ${election.contest} Cincinnati neighborhood election map`}>
          <defs><pattern id="election-missing-hatch" width="8" height="8" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><rect width="8" height="8" fill="#737b79"/><rect width="3" height="8" fill="#aeb5b3"/></pattern></defs>
          {mapData.regions.map((region) => { const result = election.neighborhoods.find((row) => row.id === region.id); const value = values.get(region.id) ?? null; const selected = region.slug === slug; const focused = region.slug === focusedSlug; return <path key={region.id} d={region.path} fill={electionFill(value, measure)} stroke={selected || focused ? "#e77c35" : "#fff"} strokeWidth={selected ? 4 : focused ? 3 : 1.45} vectorEffect="non-scaling-stroke" tabIndex={0} role="button" aria-label={`${region.name}: ${formatMapValue(value, measure)}`} aria-pressed={selected} className="cursor-pointer transition-[fill,stroke] duration-150 focus:outline-none" style={{ outline: "none" }} onFocus={() => setFocusedSlug(region.slug)} onBlur={() => setFocusedSlug(null)} onClick={() => setSlug(region.slug)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); setSlug(region.slug); } }}><title>{`${region.name}: ${formatMapValue(value, measure)}; ${(result?.directAssignmentPercent ?? 0).toFixed(0)}% directly assigned`}</title></path>; })}
        </svg>
      </div>
      <aside className="flex flex-col gap-4"><ElectionAreaPanel area={area} election={election}/><div className="border border-[#d2dcdb] bg-white p-5"><p className="eyebrow">Neighborhood estimate</p><p className="mt-2 text-2xl font-black text-[#173d4a]">{area.directAssignmentPercent?.toFixed(0) ?? "—"}% directly assigned</p><p className="mt-2 text-xs leading-5 text-[#607278]">{area.estimateStatus === "official_citywide" ? "Citywide values are official sums of Cincinnati precinct results." : `${area.matchedPrecinctCount} official precinct totals contribute to this neighborhood estimate; ${area.splitPrecinctCount} are area-weighted across neighborhood boundaries. The map presents the resulting neighborhood average without precinct lines.`}</p></div><div className="border-l-4 border-[#8759a8] bg-[#f7f1fa] p-4 text-xs leading-5 text-[#584467]"><strong>Interpretation:</strong> party percentages describe candidate or candidate-ticket vote shares, not neighborhood party registration or voter identity. “Other” includes minor-party, nonparty, and write-in candidates.</div></aside>
    </div>

    <section className="mt-6 border border-[#d2dcdb] bg-white p-5"><p className="eyebrow">Comparable {election.contest.toLowerCase()} elections</p><h2 className="mt-1 text-xl font-black text-[#173d4a]">{area.name} {election.contest.toLowerCase()} trend</h2><p className="mt-2 text-xs leading-5 text-[#607278]">Vote shares use all votes in the selected contest as the denominator. Turnout uses ballots cast divided by registered voters.</p><ElectionTrend data={trend} contest={election.contest}/></section>
    <ElectionTable election={election}/>
  </div>;
}

export function NeighborhoodElectionPanel({ data, slug }: { data: ElectionsData; slug: string }) {
  const [electionId, setElectionId] = useState(data.elections.at(-1)!.id);
  const election = data.elections.find((row) => row.id === electionId)!;
  const area = election.neighborhoods.find((row) => row.slug === slug)!;
  const trend = data.elections.filter((row) => row.contestId === election.contestId).map((row) => ({ year: row.year, ...row.neighborhoods.find((item) => item.slug === slug)! }));
  return <section className="border border-[#d4dedc] bg-white p-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Estimated election results</p><h2 className="mt-1 text-xl font-black text-[#173d4a]">Election voting</h2></div><label><span className="mb-1.5 block text-xs font-bold text-[#5b7076]">Election and contest</span><select aria-label="Neighborhood election and contest" value={electionId} onChange={(event) => setElectionId(event.target.value)} className="rounded-sm border border-[#afbfbd] bg-white px-3 py-2 text-sm font-bold text-[#173e4a]">{[...data.elections].reverse().map((item) => <option key={item.id} value={item.id}>{electionOptionLabel(item)}</option>)}</select></label></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><SmallKpi label="Turnout" value={formatElectionPercent(area.turnoutPercent)} context={`${Math.round(area.ballotsCast).toLocaleString()} modeled ballots`}/><SmallKpi label="Democratic" value={formatElectionPercent(area.democraticPercent)} context={election.democraticTicket}/><SmallKpi label="Republican" value={formatElectionPercent(area.republicanPercent)} context={election.republicanTicket}/><SmallKpi label="Other / independent" value={formatElectionPercent(area.otherPercent)} context="Minor-party, nonparty, write-in"/></div><div className="mt-4"><ShareBar area={area}/></div><div className="mt-5"><ElectionTrend data={trend} contest={election.contest}/></div><p className="mt-4 text-xs leading-5 text-[#607278]">Modeled from official precinct canvass totals using the current CAGIS precinct reference: {area.directAssignmentPercent?.toFixed(0) ?? "—"}% directly assigned; {area.splitPrecinctCount} split precincts area-weighted. <Link href="/elections" className="font-bold text-[#0a766e] underline">Open the full elections explorer</Link>.</p></section>;
}

function ElectionLegend({ measure }: { measure: ElectionMeasure }) {
  if (measure === "margin") return <div className="absolute left-1/2 top-4 z-10 w-[min(940px,calc(100%-2rem))] -translate-x-1/2 border border-[#d0dcda] bg-white/95 px-3 py-2 shadow-sm"><p className="text-center text-[0.6rem] font-black uppercase tracking-[0.09em] text-[#536970]">Republican margin ← percentage points → Democratic margin</p><div className="mt-1 grid grid-cols-[repeat(17,minmax(0,1fr))] gap-px">{marginLegend.map((step, index) => <div key={`${step.label}-${index}`} className="min-w-0 text-center"><span className="block h-3" style={{ backgroundColor: step.color }}/><span className="mt-0.5 block text-[0.48rem] font-bold text-[#536970] sm:text-[0.56rem]">{index < 8 ? `R ${step.label}` : index > 8 ? `D ${step.label}` : step.label}</span></div>)}</div></div>;
  const palette = measure === "democratic" ? blueScale : measure === "republican" ? redScale : measure === "other" ? goldScale : tealScale;
  const title = measure === "turnout" ? "Turnout" : measure === "democratic" ? "Democratic share" : measure === "republican" ? "Republican share" : "Other / independent share";
  return <div className="absolute left-1/2 top-4 z-10 w-[min(560px,calc(100%-2rem))] -translate-x-1/2 border border-[#d0dcda] bg-white/95 px-3 py-2 shadow-sm"><p className="text-center text-[0.6rem] font-black uppercase tracking-[0.09em] text-[#536970]">{title} (%)</p><div className="mt-1 grid grid-cols-8 gap-px">{palette.map((color, index) => <div key={color} className="text-center"><span className="block h-3" style={{ backgroundColor: color }}/><span className="mt-0.5 block text-[0.54rem] font-bold text-[#536970]">{index * 12.5}+</span></div>)}</div></div>;
}

function ElectionAreaPanel({ area, election }: { area: ElectionAreaResult; election: ElectionResult }) {
  return <div className="border-t-4 border-[#8759a8] bg-white p-5 shadow-sm"><p className="eyebrow">{election.year} · {election.contest}</p><h2 className="mt-2 text-xl font-black text-[#173d4a]">{area.name}</h2><div className="mt-4 grid grid-cols-2 gap-3"><SmallKpi label="Turnout" value={formatElectionPercent(area.turnoutPercent)} context={`${Math.round(area.ballotsCast).toLocaleString()} ballots · ${Math.round(area.registeredVoters).toLocaleString()} registered`}/><SmallKpi label="D–R margin" value={formatElectionPercent(area.marginPoints, true)} context={area.marginPoints === null ? "Unavailable" : area.marginPoints > 0 ? "Democratic advantage" : area.marginPoints < 0 ? "Republican advantage" : "Even"}/><SmallKpi label="Democratic" value={formatElectionPercent(area.democraticPercent)} context={election.democraticTicket}/><SmallKpi label="Republican" value={formatElectionPercent(area.republicanPercent)} context={election.republicanTicket}/></div><div className="mt-4"><ShareBar area={area}/></div></div>;
}

function ShareBar({ area }: { area: ElectionAreaResult }) {
  return <div><div className="flex h-5 overflow-hidden rounded-sm bg-[#ddd]" aria-label={`Democratic ${formatElectionPercent(area.democraticPercent)}, Republican ${formatElectionPercent(area.republicanPercent)}, other ${formatElectionPercent(area.otherPercent)}`}><span style={{ width: `${area.democraticPercent ?? 0}%`, background: "#2878bd" }}/><span style={{ width: `${area.republicanPercent ?? 0}%`, background: "#c9313c" }}/><span style={{ width: `${area.otherPercent ?? 0}%`, background: "#c58b2a" }}/></div><div className="mt-1 flex justify-between text-[0.68rem] font-bold text-[#5f7076]"><span className="text-[#1c65a2]">D {formatElectionPercent(area.democraticPercent)}</span><span className="text-[#9b5d1e]">Other {formatElectionPercent(area.otherPercent)}</span><span className="text-[#aa2430]">R {formatElectionPercent(area.republicanPercent)}</span></div></div>;
}

function ElectionTrend({ data, contest }: { data: Array<ElectionAreaResult & { year: number }>; contest: string }) {
  return <div className="h-[320px] w-full" role="img" aria-label={`${contest} turnout and vote-share trend`}><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{ top: 16, right: 20, bottom: 5, left: 0 }}><CartesianGrid stroke="#dce4e3" strokeDasharray="3 3"/><XAxis dataKey="year" tick={{ fill: "#566b72", fontSize: 11 }}/><YAxis domain={[0, 100]} tickFormatter={(value) => `${value}%`} tick={{ fill: "#566b72", fontSize: 11 }} width={44}/><Tooltip formatter={(value, name) => [`${Number(value).toFixed(1)}%`, String(name)]}/><Legend/><Line name="Turnout" type="linear" dataKey="turnoutPercent" stroke="#087e74" strokeWidth={3}/><Line name="Democratic" type="linear" dataKey="democraticPercent" stroke="#2878bd" strokeWidth={3}/><Line name="Republican" type="linear" dataKey="republicanPercent" stroke="#c9313c" strokeWidth={3}/><Line name="Other" type="linear" dataKey="otherPercent" stroke="#c58b2a" strokeWidth={2}/></LineChart></ResponsiveContainer></div>;
}

function ElectionTable({ election }: { election: ElectionResult }) {
  return <section className="mt-6 overflow-x-auto border border-[#d2dcdb] bg-white"><div className="p-5"><p className="eyebrow">All statistical areas</p><h2 className="mt-1 text-xl font-black text-[#173d4a]">{election.year} {election.contest} neighborhood estimates</h2></div><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-[#edf3f2] text-xs uppercase tracking-[0.05em] text-[#526970]"><tr><th className="px-4 py-3">Neighborhood</th><th className="px-4 py-3">Turnout</th><th className="px-4 py-3">Democratic</th><th className="px-4 py-3">Republican</th><th className="px-4 py-3">Other</th><th className="px-4 py-3">D–R margin</th><th className="px-4 py-3">Direct</th></tr></thead><tbody>{election.neighborhoods.map((row) => <tr key={row.id} className="border-t border-[#e1e8e7]"><td className="px-4 py-3 font-bold text-[#294a54]">{row.name}</td><td className="px-4 py-3 tabular">{formatElectionPercent(row.turnoutPercent)}</td><td className="px-4 py-3 tabular text-[#1f68a6]">{formatElectionPercent(row.democraticPercent)}</td><td className="px-4 py-3 tabular text-[#ad2934]">{formatElectionPercent(row.republicanPercent)}</td><td className="px-4 py-3 tabular">{formatElectionPercent(row.otherPercent)}</td><td className="px-4 py-3 font-bold tabular">{formatElectionPercent(row.marginPoints, true)}</td><td className="px-4 py-3 tabular">{formatElectionPercent(row.directAssignmentPercent)}</td></tr>)}</tbody></table></section>;
}

function SmallKpi({ label, value, context }: { label: string; value: string; context: string }) { return <div className="border border-[#d6e0df] p-4"><p className="text-[0.66rem] font-black uppercase tracking-[0.08em] text-[#667a80]">{label}</p><p className="mt-1 text-xl font-black text-[#143a4a] tabular">{value}</p><p className="mt-1 text-[0.7rem] leading-4 text-[#718187]">{context}</p></div>; }
function formatMapValue(value: number | null, measure: ElectionMeasure) { return value === null ? "Unavailable" : measure === "margin" ? `${value > 0 ? "D +" : value < 0 ? "R +" : ""}${Math.abs(value).toFixed(1)} points` : `${value.toFixed(1)}%`; }
