import geography from "@/data/manifests/geography.json";
import summaryJson from "@/data/processed/crime/current-summary.json";
import { PageShell } from "@/components/layout/page-shell";
import type { CrimeSummary } from "@/lib/crime/summary";

const sources = [
  { system: "CAGIS", title: "Cincinnati Neighborhood — SNA 2020", id: "Cincinnati_Neighborhood/FeatureServer/0", coverage: "Modern statistical geography", url: "https://services8.arcgis.com/WQtGT9bHpwcYeBTA/ArcGIS/rest/services/Cincinnati_Neighborhood/FeatureServer/0", note: "Canonical modern geometry snapshot, requested in EPSG:4326." },
  { system: "CPD STARS", title: "Reported Crime (STARS Category Offenses) on or after 6/3/2024", id: "7aqy-xrv9", coverage: "2024-06-03 onward", url: "https://data.cincinnati-oh.gov/resource/7aqy-xrv9.json", note: "Current offense-level feed. Each row represents a STARS offense." },
  { system: "CPD PDI", title: "PDI (Police Data Initiative) Crime Incidents", id: "k59e-2pvf", coverage: "Legacy feed; operational transition 2024-06-02", url: "https://data.cincinnati-oh.gov/resource/k59e-2pvf.json", note: "Public Domain per City metadata. Later reported-date outliers remain flagged for review." },
  { system: "Cincinnati Open Data", title: "SNA Boundaries 2010", id: "hshk-gimb", coverage: "2010 geography vintage", url: "https://data.cincinnati-oh.gov/Thriving-Neighborhoods/Cincinnati-Statistical-Neighborhood-Approximations-/hshk-gimb", note: "Registered as a future historical boundary import." },
];
export default function SourcesPage() { const summary = summaryJson as CrimeSummary; return <PageShell eyebrow="Audit trail" title="Sources and provenance" description="Every published number is traceable to an official source, retrieval, normalization method, and mapping version."><div className="grid gap-4">{sources.map((source) => <article key={source.id} className="grid gap-4 border border-[#d5dfde] bg-white p-5 md:grid-cols-[160px_1fr_210px]"><div><p className="eyebrow">{source.system}</p><p className="mt-2 text-xs text-[#6d7d82]">Dataset ID<br/><strong className="text-[#304f58]">{source.id}</strong></p></div><div><h2 className="text-lg font-black text-[#153b48]">{source.title}</h2><p className="mt-2 text-sm leading-6 text-[#607278]">{source.note}</p><a href={source.url} target="_blank" rel="noreferrer" className="mt-3 inline-block text-xs font-bold text-[#08766e] hover:underline">Open official source ↗</a></div><div className="border-l border-[#dce5e4] pl-4 text-xs leading-5 text-[#68797e]"><p><strong>Coverage</strong><br/>{source.coverage}</p></div></article>)}</div><div className="mt-6 grid gap-4 bg-[#143a4a] p-5 text-sm text-[#d9e6e5] md:grid-cols-3"><p><span className="block text-xs font-black uppercase tracking-[0.1em] text-[#9ed5cf]">Last crime refresh</span><span className="mt-1 block tabular">{summary.metadata.retrievedAt}</span></p><p><span className="block text-xs font-black uppercase tracking-[0.1em] text-[#9ed5cf]">Mapping version</span><span className="mt-1 block tabular">{summary.metadata.mappingVersion}</span></p><p><span className="block text-xs font-black uppercase tracking-[0.1em] text-[#9ed5cf]">Geometry checksum</span><span className="mt-1 block truncate font-mono text-xs">{geography.sourceChecksumSha256}</span></p></div></PageShell>; }
