import { PageShell } from "@/components/layout/page-shell";

const sections = [
  ["What is an SNA?", "A Statistical Neighborhood Approximation is the City Planning geography used to relate neighborhood statistics to census geography. It is distinct from Community Council boundaries, which may overlap and are not used here for exclusive aggregation."],
  ["Which crime source drives current views?", "The CPD neighborhood reports drive the map, rankings, comparison, and profile totals because they are fresher. They are preliminary aggregate reports, not offense rows. STARS remains the separate offense-level source through its own cutoff. One current source PDF (Villages at Roll Hill / Fay Apartments) contains published YTD subtotal-component inconsistencies; all published values are preserved and the exception is reported."],
  ["How is violent crime defined?", "The current aggregate layer uses CPD's published Part 1 Violent total. STARS offense detail preserves homicide, rape, robbery, aggravated assault, and the separately reported Strangulation category without pretending the two source grains are interchangeable."],
  ["How are historical PDI categories mapped?", "PDI Homicide, Rape, Robbery, and Aggravated Assaults form violent crime. Burglary/Breaking Entering and Theft form property crime. Unauthorized Use, Part 2 Minor, and blank UCR groups are retained but excluded from Part I totals. The 2024 chart marker identifies the change from incident rows to STARS offense rows."],
  ["Which individual offenses can I select?", "Homicide, rape, robbery, aggravated assault, burglary, and larceny/theft are available throughout the 2011–present panel. Motor-vehicle theft and Strangulation become separately available with the 2024 STARS transition. Unsupported earlier observations display as unavailable, never as zero."],
  ["How is YTD compared?", "The current year begins January 1 and ends on the source cutoff date. Prior YTD uses January 1 through the same month and day in the preceding year. A partial current year is never compared with a full prior year."],
  ["What is the 28-day comparison?", "Current 28 days means D−27 through D, inclusive. Previous 28 days means D−55 through D−28. When the prior count is zero, the explorer reports new activity rather than an infinite percent change."],
  ["Why show absolute change?", "Small denominators make percentages volatile. A change from 1 to 5 is +400% but only four additional offenses, so the interface shows current, prior, absolute, and percent change together."],
  ["What changed in June 2024?", "Cincinnati transitioned from the legacy PDI records system to STARS on June 3, 2024. The feeds have different schemas and grains, so they enter separate adapters and mappings rather than being concatenated."],
  ["How are rates calculated?", "A selected crime-type rate divides its count by that year’s documented population denominator and multiplies by 1,000. The series uses official 2010 and 2020 City Planning Census SNA anchors, linear interpolation for 2011–2019, and a visibly labeled 2020 carry-forward after 2020. Citywide rates use direct Citywide anchors because published neighborhood populations do not add to the direct Citywide profile."],
  ["How does the change map work?", "Every map measure—including reported count and rate per 1,000—is colored by the signed change from its matching prior period. Every nonzero decrease is green and every nonzero increase is red. Symmetric bands at 2.5, 5, 7.5, 15, 20, 25, and 50 percent increase saturation with magnitude. Only exact zero is gray; unavailable values use gray hatching. A zero baseline is labeled new activity rather than an infinite percentage."],
  ["What do the election percentages mean?", "Democratic, Republican, and other percentages are candidate or candidate-ticket vote shares, not voter registration or party identification. The denominator is all votes in the selected President, Governor, or U.S. Senate contest; ballot undervotes are excluded. Turnout is official ballots cast divided by registered voters at precinct level."],
  ["How are election results assigned to neighborhoods?", "Official Hamilton County precinct canvass totals for the 2016–2024 presidential and midterm panels are matched to the official current CAGIS precinct reference. Each precinct is intersected with SNA 2020 polygons and split by geographic area. Citywide totals are official; neighborhood values are modeled estimates. The public map shows one averaged result per neighborhood with no precinct overlay; direct-allocation percentages quantify dependence on split precincts."],
  ["What does the Police budget series measure?", "The financial page sums CURRENT_BUDGET for the Police department and published Police bureau rows in the official Cincinnati Financial System dataset. These are budgeted or appropriated dollars, not audited actual expenditures. FY2013 covers only January through June during the City’s fiscal-calendar transition; FY2014 onward covers July 1 through June 30. FY2005 is unavailable and remains blank."],
  ["How is budget attributed to neighborhoods?", "For a selected fiscal year and crime category, the model divides the citywide Police budget by citywide reported crimes, then multiplies that common rate by each neighborhood’s reported-crime count. Unassigned crime geography receives its own allocation so modeled dollars reconcile to the full budget. The result is labeled crime-share attributed budget: it is not actual neighborhood spending, staffing, workload, service delivery, or a causal cost of crime."],
  ["What demographic data are included?", "Neighborhood profiles retain the official 2016–2020 ACS 5-year estimates and published 90% margins of error from City Planning’s SNA reports. Derived percentages propagate numerator and denominator uncertainty approximately; combined map regions combine member MOEs by root-sum-of-squares. Image-only tables remain unavailable until independently transcribed and checked."],
  ["How is history handled?", "Calendar years 2011–2025 and same-date YTD periods through 2026 retain their source system, grain, geography status, and unassigned totals. PDI geography uses SNA, CPD-neighborhood, then community-council labels before leaving unresolved rows in a citywide bucket. Historical neighborhood values are displayed on 2020 SNA geography as a visible proxy."],
];
export default function MethodologyPage() { return <PageShell eyebrow="Definitions and limits" title="Methodology" description="Concise rules for interpreting every statistic in the explorer."><div className="grid gap-4 md:grid-cols-2">{sections.map(([title, text]) => <section key={title} className="border border-[#d5dfde] bg-white p-5"><h2 className="text-lg font-black text-[#153b48]">{title}</h2><p className="mt-2 text-sm leading-6 text-[#607278]">{text}</p></section>)}</div></PageShell>; }
