import { PageShell } from "@/components/layout/page-shell";

const sections = [
  ["What is an SNA?", "A Statistical Neighborhood Approximation is the City Planning geography used to relate neighborhood statistics to census geography. It is distinct from Community Council boundaries, which may overlap and are not used here for exclusive aggregation."],
  ["Which crime source drives current views?", "The CPD neighborhood reports drive the map, rankings, comparison, and profile totals because they are fresher. They are preliminary aggregate reports, not offense rows. STARS remains the separate offense-level source through its own cutoff. One current source PDF (Villages at Roll Hill / Fay Apartments) contains published YTD subtotal-component inconsistencies; all published values are preserved and the exception is reported."],
  ["How is violent crime defined?", "The current aggregate layer uses CPD's published Part 1 Violent total. STARS offense detail preserves homicide, rape, robbery, aggravated assault, and the separately reported Strangulation category without pretending the two source grains are interchangeable."],
  ["How is YTD compared?", "The current year begins January 1 and ends on the source cutoff date. Prior YTD uses January 1 through the same month and day in the preceding year. A partial current year is never compared with a full prior year."],
  ["What is the 28-day comparison?", "Current 28 days means D−27 through D, inclusive. Previous 28 days means D−55 through D−28. When the prior count is zero, the explorer reports new activity rather than an infinite percent change."],
  ["Why show absolute change?", "Small denominators make percentages volatile. A change from 1 to 5 is +400% but only four additional offenses, so the interface shows current, prior, absolute, and percent change together."],
  ["What changed in June 2024?", "Cincinnati transitioned from the legacy PDI records system to STARS on June 3, 2024. The feeds have different schemas and grains, so they enter separate adapters and mappings rather than being concatenated."],
  ["How are rates calculated?", "The violent YTD rate divides the CPD report's Part 1 Violent count by the official 2020 City Planning neighborhood-profile population and multiplies by 1,000. For each of the three combined CAGIS polygons, member counts and populations are summed. The published neighborhood populations are not additive to the direct Citywide profile, so the city rate uses the direct Citywide population."],
  ["How is history handled?", "Historical values retain source citation, source-quality class, page or table reference, boundary version, and reconstruction status. Statistics are not mapped onto 2020 geometry without a visible native/proxy/crosswalk designation."],
];
export default function MethodologyPage() { return <PageShell eyebrow="Definitions and limits" title="Methodology" description="Concise rules for interpreting every statistic in the explorer."><div className="grid gap-4 md:grid-cols-2">{sections.map(([title, text]) => <section key={title} className="border border-[#d5dfde] bg-white p-5"><h2 className="text-lg font-black text-[#153b48]">{title}</h2><p className="mt-2 text-sm leading-6 text-[#607278]">{text}</p></section>)}</div></PageShell>; }
