"use client";

import { useState } from "react";
import { formatChange, type CrimeSummary } from "@/lib/crime/summary";

export function ComparisonTool({ summary }: { summary: CrimeSummary }) {
  const defaults = [summary.neighborhoods.find((row) => row.name === "Mt. Airy")?.slug ?? summary.neighborhoods[0].slug, summary.neighborhoods.find((row) => row.name === "Westwood")?.slug ?? summary.neighborhoods[1].slug];
  const [selected, setSelected] = useState(defaults);
  const update = (index: number, slug: string) => setSelected((current) => current.map((value, position) => position === index ? slug : value));
  const add = () => selected.length < 4 && setSelected((current) => [...current, summary.neighborhoods.find((row) => !current.includes(row.slug))?.slug ?? summary.neighborhoods[0].slug]);
  const rows = selected.map((slug) => summary.neighborhoods.find((row) => row.slug === slug)!);
  return <div><div className="mb-5 flex flex-wrap items-end gap-3">{selected.map((slug, index) => <label key={index}><span className="mb-1 block text-xs font-bold text-[#5b7076]">Area {index + 1}</span><select value={slug} onChange={(event) => update(index, event.target.value)} className="rounded-sm border border-[#afbfbd] bg-white px-3 py-2 text-sm font-bold text-[#173e4a]">{summary.neighborhoods.map((row) => <option key={row.slug} value={row.slug}>{row.name}</option>)}</select></label>)}<button onClick={add} disabled={selected.length >= 4} className="rounded-sm bg-[#0a766e] px-4 py-2 text-sm font-bold text-white disabled:opacity-40">+ Add area</button></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{rows.map((row) => <article key={row.slug} className="border-t-4 border-[#0a766e] bg-white p-5 shadow-sm"><p className="eyebrow">Statistical area</p><h2 className="mt-2 text-xl font-black text-[#143a4a]">{row.name}</h2><dl className="mt-5 space-y-3 text-sm"><Metric label="Violent YTD" value={`${row.currentYtd.violent}`} detail={`${row.priorYtd.violent} prior`} /><Metric label="Violent per 1,000" value={row.rates?.violentYtdPer1000?.toFixed(1) ?? "Unavailable"} detail={`${row.population?.toLocaleString() ?? "No"} population (${row.populationYear ?? "—"})`} /><Metric label="Violent YTD change" value={formatChange(row.changes.violentYtd)} detail={`${row.currentYtd.violent - row.priorYtd.violent >= 0 ? "+" : ""}${row.currentYtd.violent - row.priorYtd.violent} offenses`} /><Metric label="Violent, latest 28 days" value={`${row.current28.violent}`} detail={`${row.previous28.violent} previous`} /><Metric label="Property YTD" value={`${row.currentYtd.property}`} detail={`${row.priorYtd.property} prior`} /><Metric label="Total Part I YTD" value={`${row.currentYtd.totalPart1}`} detail={`${row.priorYtd.totalPart1} prior`} /></dl></article>)}</div></div>;
}
function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="flex items-end justify-between gap-3 border-b border-[#e2e9e8] pb-2"><dt className="text-[#65767b]">{label}</dt><dd className="text-right"><span className="block font-black text-[#173e4a] tabular">{value}</span><span className="block text-[0.68rem] text-[#819095] tabular">{detail}</span></dd></div>; }
